import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "./components/Menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Alpha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-blue-200 relative`}
      >
        <h1 className='text-3xl md:text-4xl lg:text-5xl font-semibold text-center pt-5 md:pt-10 text-[#31326F]'>Al<span className='text-[#637AB9]'>pha</span></h1>
        <div className="fixed top-5 left-5">
          <Menu></Menu>
        </div>
        {children}
      </body>
    </html>
  );
}
